Feature/ros
sbgisen/yolo_tracking pull request #1
Opened 2024-01-18 05:16 UTC by Tacha-S

## Summary

検出した物体の特徴量ベクトルを推定するノードと、
それを用いたRGB画像での物体トラッキングノードの追加

- ref https://github.com/sbgisen/spencer_people_tracking/pull/7

## Detail

## Impact

## Test

  

## Attention

2024-01-18 11:22 UTC, jsupratman13 requested changes

2024-01-18 11:22 UTC, jsupratman13 commented on CMakeLists.txt
> +  PROGRAMS scripts/completion.py
completion.py無くない？

2024-01-18 11:22 UTC, jsupratman13 commented on Pipfile
> +python_version = "3.6"
python3.6 にする必要はなんですか

2024-01-18 11:22 UTC, jsupratman13 commented on package.xml
> +  <depend>rospy</depend>
jsk_recognitionも追加

2024-01-18 23:51 UTC, Tacha-S commented on Pipfile
> +python_version = "3.6"
3.8で大丈夫なので修正します。

2024-01-19 00:53 UTC, jsupratman13 requested changes
>  それを用いたRGB画像での物体トラッキングノードの追加

トラッキングてこんなもの？


https://github.com/sbgisen/yolo_tracking/assets/7608312/9854b698-d7de-4855-bf90-e78a4f295ed9




後 tracker.pyを実行するとログがストリーミングするけどなんとかできない？

2024-01-19 00:53 UTC, jsupratman13 commented on launch/estimate_feature.launch
> +    <remap from="results" to="/soar/perception/object_detection/instance_segmentation/output/class"/>
`image` `rects`, `results`に導入する引数があるといい

2024-01-19 01:15 UTC, Tacha-S commented
> トラッキングてこんなもの？

カルマンフィルタでのトラッキングなんでジャンプの激しいデータはそんなもんなんじゃないですか？

> 後 tracker.pyを実行するとログがストリーミングするけどなんとかできない？

何のログがでます？

2024-01-19 02:00 UTC, jsupratman13 commented
> 何のログがでます？

移動中なので後で明確なログを貼りますが
```
[[0, 0.08]]
```
とかweight見たいなログが出てくる

2024-01-19 03:37 UTC, jsupratman13 commented
> 移動中なので後で明確なログを貼りますが


こんな感じ．tracker.pyのトピックをsoarに合わせると以下のログがストリーミングする
```
2024-01-19 12:35:21.776 | SUCCESS  | boxmot.appearance.reid_model_factory:load_pretrained_weights:207 - Successfully loaded pretrained weights from "osnet_x0_25_msmt17.pt"
2024-01-19 12:35:21.777 | WARNING  | boxmot.appearance.reid_model_factory:load_pretrained_weights:211 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifi
er.bias')                                                                                              
[[1. 0.]                                                                                               
 [0. 1.]]                                                                                              
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[0.99886769 0.        ]
 [0.         0.99924905]] 
[[0.99952013 0.        ]
 [0.         0.99977594]] 
 ```

2024-01-19 04:24 UTC, Tacha-S commented
最新のboxmot(10.0.51)だとそのログが出るようなので、10.0.47に固定しました

2024-01-19 05:10 UTC, jsupratman13 approved these changes

2024-01-19 05:10 UTC, merged